services:

    #
    # Commands
    #
    elcodi.plugins_load_command:
        class: %elcodi.plugins_load_command.class%
        arguments:
            - @elcodi.plugin_manager
        tags:
            -  { name: console.command }
