services:

    #
    # Commands
    #
    elcodi.command.plugins_load:
        class: Elcodi\Component\Plugin\Command\PluginsLoadCommand
        arguments:
            - @elcodi.manager.plugin
        tags:
            -  { name: console.command }
