services:

    #
    # Repositories
    #
    elcodi.repository.plugin:
        parent: elcodi.abstract_repository
        class: Elcodi\Component\Plugin\Repository\PageRepository
        arguments: [ %elcodi.entity.plugin.class% ]
