services:

    #
    # Services
    #
    elcodi.manager.template:
        class: Elcodi\Component\Template\Services\TemplateManager
        arguments:
            - @kernel
            - @elcodi.manager.configuration

    elcodi.manager.plugin:
        class: Elcodi\Component\Plugin\Services\PluginManager
        arguments:
            - @kernel
            - @elcodi.manager.configuration
