services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.plugin:
        class: Elcodi\Component\Plugin\Twig\PluginExtension
        arguments:
            - @elcodi.plugin_manager
        tags:
            - { name: twig.extension }

    elcodi.twig_extension.plugin_hook:
        class: Elcodi\Component\Plugin\Twig\HookExtension
        arguments:
            - @elcodi.hook_system
        tags:
            - { name: twig.extension }
