services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.plugin_hook:
        class: %elcodi.twig_extension.plugin_hook.class%
        arguments:
            - @elcodi.hook_system
        tags:
            - { name: twig.extension }
